### ISSUE TITLE
I can not get VEVO video link on youtube

### ISSUE THREAD

**Issue by haibk** [phiexz/rapidleech#1]
Hi!
I can not get VEVO videos on youtube link
Example: https://www.youtube.com/watch?v=wyK7YuwUWsU
I get the message: Error while decoding [16 973] [en_US-vflkX1eCa / base]: Can not find the decoder function
Please update so I can get the link
Thank you very much

**Comment by phiexz** [comment]
sorry for long response, it should be fixed now
